[project]
name = "plox"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mypy>=1.19.1",
    "platformdirs>=4.5.1",
    "prompt-toolkit>=3.0.51",
    "pytest>=9.0.2",
    "termcolor>=3.1.0",
]

[project.scripts]
plox = "plox.__main__:main"
